"""Raw ELF600 vendor wiki (elf.co.jp) access — bundled wiki_dump.json (~67 pages).

Generated by ``scripts/crawl_wiki.py`` from PukiWiki at https://elf.co.jp/.
Curated to skip session-key / placeholder / private pages.

Functions:
    load_wiki_dump()                  -> dict[str, dict]
    list_wiki_pages()                 -> list of {name, url, char_count, title}
    search_wiki(query, top_k=10)      -> ranked snippet matches
    get_wiki_page(name, max_chars=...) -> full extracted text
"""
from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources
from typing import Any


@lru_cache(maxsize=1)
def load_wiki_dump() -> dict[str, dict[str, Any]]:
    data = resources.files("elf_mcp_server").joinpath("wiki_dump.json").read_text(encoding="utf-8")
    return json.loads(data)


def list_wiki_pages() -> list[dict[str, Any]]:
    dump = load_wiki_dump()
    out = []
    for name, meta in sorted(dump.items()):
        out.append({
            "name": name,
            "url": meta.get("url", ""),
            "title": meta.get("title", ""),
            "char_count": meta.get("char_count", 0),
        })
    return out


def search_wiki(query: str, top_k: int = 10) -> list[dict[str, Any]]:
    dump = load_wiki_dump()
    keywords = [k.strip() for k in query.split() if k.strip()]
    if not keywords:
        return []
    hits = []
    for name, meta in dump.items():
        text = meta.get("text", "")
        text_lower = text.lower()
        scores = [text_lower.count(kw.lower()) for kw in keywords]
        if not all(s > 0 for s in scores):
            continue
        score = sum(scores)
        first_pos = text_lower.find(keywords[0].lower())
        snip_start = max(0, first_pos - 80)
        snip_end = min(len(text), first_pos + 220)
        snippet = text[snip_start:snip_end].replace("\n", " ").strip()
        if snip_start > 0:
            snippet = "..." + snippet
        if snip_end < len(text):
            snippet = snippet + "..."
        hits.append({
            "name": name,
            "url": meta.get("url", ""),
            "title": meta.get("title", ""),
            "score": score,
            "snippet": snippet,
        })
    hits.sort(key=lambda h: -h["score"])
    return hits[:top_k]


def get_wiki_page(name: str, max_chars: int = 30000) -> dict[str, Any]:
    dump = load_wiki_dump()
    meta = dump.get(name)
    if not meta:
        candidates = [p for p in dump if name in p]
        if len(candidates) == 1:
            name = candidates[0]
            meta = dump[name]
        else:
            return {
                "name": name,
                "error": f"not found (similar: {candidates[:5]})" if candidates
                         else "not found in wiki_dump (use elf_wiki_index)",
            }
    text = meta.get("text", "")
    truncated = len(text) > max_chars
    if truncated:
        text = text[:max_chars] + f"\n\n[... truncated, full length: {meta.get('char_count', 0)} chars]"
    return {
        "name": name,
        "url": meta.get("url", ""),
        "title": meta.get("title", ""),
        "text": text,
        "char_count": meta.get("char_count", 0),
        "truncated": truncated,
    }
